# SPDX-License-Identifier: MIT
"""The widest net for the least code.

`example/` regenerates its four outputs byte for byte: nothing in that pipeline reads a
clock, so a golden comparison needs no time faking at all. Any silent change to a number,
a page or the icon shows up here.
"""
import filecmp
import json
import os

import pytest

from conftest import ROOT, run

OUTPUTS = ["kpi.json", "spans.json", "icon.svg", "index.html"]


def test_example_regenerates_byte_for_byte(workspace):
    wd = workspace("example")
    for script in ("measure.py", "build_icon.py", "build_page.py"):
        r = run(wd, script)
        assert r.returncode == 0, f"{script}: {r.stderr}"
    for name in OUTPUTS:
        assert filecmp.cmp(wd / name, os.path.join(ROOT, "example", name), shallow=False), \
            f"{name} is not byte-identical to the committed example"


def test_case001_measures_the_same(workspace, tmp_path):
    """cases/001 carries its own scripts on purpose, so running it as it stands tests
    nothing about today's skill. Run today's scripts over its inputs instead — and only
    for the two outputs that are still expected to match: its icon and its page were
    generated by older versions and are historical artefacts of the case."""
    wd = workspace("cases/001")
    r = run(wd, "measure.py")
    assert r.returncode == 0, r.stderr
    for name in ("kpi.json", "spans.json"):
        assert filecmp.cmp(wd / name, os.path.join(ROOT, "cases", "001", name),
                           shallow=False), f"{name} drifted on the validation case"


def test_example_kpi_reports_both_axes(workspace):
    wd = workspace("example")
    assert run(wd, "measure.py").returncode == 0
    kpi = json.loads((wd / "kpi.json").read_text(encoding="utf-8"))
    assert kpi["integrity"] is True
    assert kpi["unexplained"] == []
    assert "by_phase" in kpi and kpi["by_phase"], "the breakdown by phase is not optional"
