# SPDX-License-Identifier: MIT
"""The widest net for the least code.

`example/` regenerates its four outputs byte for byte: nothing in that pipeline reads a
clock, so a golden comparison needs no time faking at all. Any silent change to a number,
a page or the icon shows up here.
"""
import filecmp
import json
import os

import pytest

from conftest import ROOT, run

OUTPUTS = ["kpi.json", "spans.json", "icon.svg", "index.html"]


def test_example_regenerates_byte_for_byte(workspace):
    wd = workspace("example")
    for script in ("measure.py", "build_icon.py", "build_page.py"):
        r = run(wd, script)
        assert r.returncode == 0, f"{script}: {r.stderr}"
    for name in OUTPUTS:
        assert filecmp.cmp(wd / name, os.path.join(ROOT, "example", name), shallow=False), \
            f"{name} is not byte-identical to the committed example"


def test_case001_measures_the_same(workspace, tmp_path):
    """cases/001 carries its own scripts on purpose, so running it as it stands tests
    nothing about today's skill. Run today's scripts over its inputs instead — and only
    for the two outputs that are still expected to match: its icon and its page were
    generated by older versions and are historical artefacts of the case.

    The comparison is on the measured values, not on the bytes of the files. What must
    not drift is the measurement: the totals, the two aggregate shares, the phases and
    what each of them weighs. A file compared byte for byte also fails when a key is
    added that moves no number — noise, and the reason this assertion had to be
    loosened once already — and it passes when a value changes representation while
    staying equal, which is the one thing it was written to catch."""
    wd = workspace("cases/001")
    r = run(wd, "measure.py")
    assert r.returncode == 0, r.stderr

    def measured(ss):
        """A span's measurement is its text, its weight and its two attributions."""
        return [{k: s[k] for k in ("block", "text", "words", "lex", "idea", "phase")}
                for s in ss]

    frozen_dir = os.path.join(ROOT, "cases", "001")
    frozen = json.loads(open(os.path.join(frozen_dir, "kpi.json"), encoding="utf-8").read())
    today = json.loads((wd / "kpi.json").read_text(encoding="utf-8"))
    for k in ("words", "spans", "ai_lexical", "ai_ideational", "lexical", "ideational"):
        assert today[k] == frozen[k], f"{k} drifted on the validation case"

    assert list(today["by_phase"]) == list(frozen["by_phase"]), \
        "the phases of the validation case changed"
    for phase, was in frozen["by_phase"].items():
        now = today["by_phase"][phase]
        assert now["words"] == was["words"], f"{phase}: the word count drifted"
        # The frozen file names the figure "ai". It was the lexical share all along —
        # that it did not say so is the defect this case was filed from.
        assert now["ai_lexical"] == was["ai"], f"{phase}: the lexical share drifted"

    assert measured(json.loads((wd / "spans.json").read_text(encoding="utf-8"))) == \
        measured(json.loads(open(os.path.join(frozen_dir, "spans.json"),
                                 encoding="utf-8").read())), \
        "the spans drifted on the validation case"


def test_example_kpi_reports_both_axes(workspace):
    wd = workspace("example")
    assert run(wd, "measure.py").returncode == 0
    kpi = json.loads((wd / "kpi.json").read_text(encoding="utf-8"))
    assert kpi["integrity"] is True
    assert kpi["unexplained"] == []
    assert "by_phase" in kpi and kpi["by_phase"], "the breakdown by phase is not optional"
    for phase, d in kpi["by_phase"].items():
        # Both axes, and neither of them under a name that does not say which it is:
        # the note prescribed in reference/disclosures.md takes its per-phase figure
        # from here, and a key called "ai" was published as if it were the ideational one.
        assert set(d) == {"words", "ai_lexical", "ai_ideational"}, \
            f"{phase}: the breakdown does not carry both axes, each named"
